import {
  BatBoundaryFrequencyCalculator,
  BatBoundaryPercentageCalculator,
  BatBoundaryRunsCalculator,
  BatFoursCalculator,
  BatFoursPercentageCalculator,
  BatRunsPerBallCalculator,
  BatRunsPerBoundaryCalculator,
  BatSixesCalculator,
  BatSixesPercentageCalculator,
  BatStrikeRateCalculator,
} from '../calculators/batting/BattingScoringCalculators'
import {
  MetricCategory,
  MetricLevel,
  type MetricDefinition,
} from './types'

const version = '1.0.0'

export const battingScoringMetricDefinitions: readonly MetricDefinition[] = [
  {
    id: 'bat.strike_rate',
    name: 'Strike Rate',
    category: MetricCategory.Batting,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new BatStrikeRateCalculator(),
  },
  {
    id: 'bat.boundary_runs',
    name: 'Boundary Runs',
    category: MetricCategory.Batting,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new BatBoundaryRunsCalculator(),
  },
  {
    id: 'bat.boundary_percentage',
    name: 'Boundary Percentage',
    category: MetricCategory.Batting,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new BatBoundaryPercentageCalculator(),
  },
  {
    id: 'bat.boundary_frequency',
    name: 'Boundary Frequency',
    category: MetricCategory.Batting,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new BatBoundaryFrequencyCalculator(),
  },
  {
    id: 'bat.runs_per_ball',
    name: 'Runs Per Ball',
    category: MetricCategory.Batting,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new BatRunsPerBallCalculator(),
  },
  {
    id: 'bat.runs_per_boundary',
    name: 'Runs Per Boundary',
    category: MetricCategory.Batting,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new BatRunsPerBoundaryCalculator(),
  },
  {
    id: 'bat.fours',
    name: 'Fours',
    category: MetricCategory.Batting,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new BatFoursCalculator(),
  },
  {
    id: 'bat.sixes',
    name: 'Sixes',
    category: MetricCategory.Batting,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new BatSixesCalculator(),
  },
  {
    id: 'bat.fours_percentage',
    name: 'Fours Percentage',
    category: MetricCategory.Batting,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new BatFoursPercentageCalculator(),
  },
  {
    id: 'bat.sixes_percentage',
    name: 'Sixes Percentage',
    category: MetricCategory.Batting,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new BatSixesPercentageCalculator(),
  },
]
