import {
  BatBallsFacedCalculator,
  BatDoubleHundredsCalculator,
  BatFiftiesCalculator,
  BatHighestScoreCalculator,
  BatHundredsCalculator,
  BatInningsCalculator,
  BatMatchesCalculator,
  BatNotOutsCalculator,
  BatRunsCalculator,
} from '../calculators/batting/BattingVolumeCalculators'
import {
  MetricCategory,
  MetricLevel,
  type MetricDefinition,
} from './types'

const version = '1.0.0'

export const battingVolumeMetricDefinitions: readonly MetricDefinition[] = [
  {
    id: 'bat.matches',
    name: 'Batting Matches',
    category: MetricCategory.Batting,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new BatMatchesCalculator(),
  },
  {
    id: 'bat.innings',
    name: 'Batting Innings',
    category: MetricCategory.Batting,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new BatInningsCalculator(),
  },
  {
    id: 'bat.runs',
    name: 'Batting Runs',
    category: MetricCategory.Batting,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new BatRunsCalculator(),
  },
  {
    id: 'bat.balls_faced',
    name: 'Balls Faced',
    category: MetricCategory.Batting,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new BatBallsFacedCalculator(),
  },
  {
    id: 'bat.not_outs',
    name: 'Not Outs',
    category: MetricCategory.Batting,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new BatNotOutsCalculator(),
  },
  {
    id: 'bat.highest_score',
    name: 'Highest Score',
    category: MetricCategory.Batting,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new BatHighestScoreCalculator(),
  },
  {
    id: 'bat.fifties',
    name: 'Fifties',
    category: MetricCategory.Batting,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new BatFiftiesCalculator(),
  },
  {
    id: 'bat.hundreds',
    name: 'Hundreds',
    category: MetricCategory.Batting,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new BatHundredsCalculator(),
  },
  {
    id: 'bat.double_hundreds',
    name: 'Double Hundreds',
    category: MetricCategory.Batting,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new BatDoubleHundredsCalculator(),
  },
]
