import {
  BowlAverageCalculator,
  BowlBallsCalculator,
  BowlEconomyCalculator,
  BowlInningsCalculator,
  BowlMaidensCalculator,
  BowlMatchesCalculator,
  BowlNoBallsCalculator,
  BowlOversCalculator,
  BowlRunsConcededCalculator,
  BowlStrikeRateCalculator,
  BowlWicketsCalculator,
  BowlWidesCalculator,
} from '../calculators/bowling/BowlingCoreCalculators'
import {
  MetricCategory,
  MetricLevel,
  type MetricDefinition,
} from './types'

const version = '1.0.0'

export const bowlingCoreMetricDefinitions: readonly MetricDefinition[] = [
  {
    id: 'bowl.matches',
    name: 'Bowling Matches',
    category: MetricCategory.Bowling,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new BowlMatchesCalculator(),
  },
  {
    id: 'bowl.innings',
    name: 'Bowling Innings',
    category: MetricCategory.Bowling,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new BowlInningsCalculator(),
  },
  {
    id: 'bowl.overs',
    name: 'Overs',
    category: MetricCategory.Bowling,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new BowlOversCalculator(),
  },
  {
    id: 'bowl.balls',
    name: 'Balls',
    category: MetricCategory.Bowling,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new BowlBallsCalculator(),
  },
  {
    id: 'bowl.maidens',
    name: 'Maidens',
    category: MetricCategory.Bowling,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new BowlMaidensCalculator(),
  },
  {
    id: 'bowl.runs_conceded',
    name: 'Runs Conceded',
    category: MetricCategory.Bowling,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new BowlRunsConcededCalculator(),
  },
  {
    id: 'bowl.wickets',
    name: 'Wickets',
    category: MetricCategory.Bowling,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new BowlWicketsCalculator(),
  },
  {
    id: 'bowl.no_balls',
    name: 'No Balls',
    category: MetricCategory.Bowling,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new BowlNoBallsCalculator(),
  },
  {
    id: 'bowl.wides',
    name: 'Wides',
    category: MetricCategory.Bowling,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new BowlWidesCalculator(),
  },
  {
    id: 'bowl.economy',
    name: 'Economy',
    category: MetricCategory.Bowling,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new BowlEconomyCalculator(),
  },
  {
    id: 'bowl.average',
    name: 'Bowling Average',
    category: MetricCategory.Bowling,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new BowlAverageCalculator(),
  },
  {
    id: 'bowl.strike_rate',
    name: 'Bowling Strike Rate',
    category: MetricCategory.Bowling,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new BowlStrikeRateCalculator(),
  },
]
