import {
  BatConversionCalculator,
  BatDismissalResilienceCalculator,
  BatEffectivenessCalculator,
} from '../calculators/batting/BattingExpandedCompositeCalculators'
import {
  BatConsistencyCalculator,
  BatScoringConsistencyCalculator,
} from '../calculators/batting/BattingConsistencyCompositeCalculators'
import {
  BatBoundaryIntentCalculator,
  BatIntentCalculator,
} from '../calculators/batting/BattingIntentCompositeCalculators'
import {
  BowlControlCalculator,
  BowlDisciplineCalculator,
  BowlEffectivenessCalculator,
  BowlRunControlCalculator,
  BowlWicketEfficiencyCalculator,
  BowlWicketThreatCalculator,
} from '../calculators/bowling/BowlingCompositeCalculators'
import {
  FieldActivityCalculator,
  FieldCatchingImpactCalculator,
  FieldDismissalInvolvementCalculator,
  FieldImpactCalculator,
  FieldReliabilityCalculator,
  FieldRunOutImpactCalculator,
} from '../calculators/fielding/FieldingCompositeCalculators'
import {
  MetricCategory,
  MetricLevel,
  type MetricDefinition,
} from './types'

const version = '1.0.0'

export const compositeMetricDefinitions: readonly MetricDefinition[] = [
  {
    id: 'bat.intent',
    name: 'Batting Intent',
    category: MetricCategory.Batting,
    level: MetricLevel.Composite,
    dependencies: ['bat.strike_rate', 'bat.boundary_percentage', 'bat.runs_per_ball'],
    version,
    calculator: new BatIntentCalculator(),
  },
  {
    id: 'bat.boundary_intent',
    name: 'Boundary Intent',
    category: MetricCategory.Batting,
    level: MetricLevel.Composite,
    dependencies: ['bat.boundary_percentage'],
    version,
    calculator: new BatBoundaryIntentCalculator(),
  },
  {
    id: 'bat.consistency',
    name: 'Batting Consistency',
    category: MetricCategory.Batting,
    level: MetricLevel.Composite,
    dependencies: [
      'bat.innings',
      'bat.average',
      'bat.fifties',
      'bat.hundreds',
      'bat.ducks',
    ],
    version,
    calculator: new BatConsistencyCalculator(),
  },
  {
    id: 'bat.scoring_consistency',
    name: 'Scoring Consistency',
    category: MetricCategory.Batting,
    level: MetricLevel.Composite,
    dependencies: ['bat.innings', 'bat.fifties', 'bat.hundreds', 'bat.ducks'],
    version,
    calculator: new BatScoringConsistencyCalculator(),
  },
  {
    id: 'bat.effectiveness',
    name: 'Batting Effectiveness',
    category: MetricCategory.Batting,
    level: MetricLevel.Composite,
    dependencies: [
      'bat.intent',
      'bat.consistency',
      'bat.scoring_consistency',
      'bat.boundary_intent',
    ],
    version,
    calculator: new BatEffectivenessCalculator(),
  },
  {
    id: 'bat.conversion',
    name: 'Batting Conversion',
    category: MetricCategory.Batting,
    level: MetricLevel.Composite,
    dependencies: ['bat.innings', 'bat.fifties', 'bat.hundreds', 'bat.double_hundreds'],
    version,
    calculator: new BatConversionCalculator(),
  },
  {
    id: 'bat.dismissal_resilience',
    name: 'Dismissal Resilience',
    category: MetricCategory.Batting,
    level: MetricLevel.Composite,
    dependencies: ['bat.innings', 'bat.outs', 'bat.not_outs', 'bat.ducks', 'bat.average'],
    version,
    calculator: new BatDismissalResilienceCalculator(),
  },
  {
    id: 'bowl.control',
    name: 'Bowling Control',
    category: MetricCategory.Bowling,
    level: MetricLevel.Composite,
    dependencies: [
      'bowl.economy',
      'bowl.wides',
      'bowl.no_balls',
      'bowl.overs',
      'bowl.maidens',
    ],
    version,
    calculator: new BowlControlCalculator(),
  },
  {
    id: 'bowl.wicket_threat',
    name: 'Wicket Threat',
    category: MetricCategory.Bowling,
    level: MetricLevel.Composite,
    dependencies: ['bowl.wickets', 'bowl.innings', 'bowl.matches'],
    version,
    calculator: new BowlWicketThreatCalculator(),
  },
  {
    id: 'bowl.effectiveness',
    name: 'Bowling Effectiveness',
    category: MetricCategory.Bowling,
    level: MetricLevel.Composite,
    dependencies: [
      'bowl.economy',
      'bowl.average',
      'bowl.strike_rate',
      'bowl.wickets',
      'bowl.innings',
    ],
    version,
    calculator: new BowlEffectivenessCalculator(),
  },
  {
    id: 'bowl.run_control',
    name: 'Bowling Run Control',
    category: MetricCategory.Bowling,
    level: MetricLevel.Composite,
    dependencies: ['bowl.economy', 'bowl.maidens', 'bowl.overs'],
    version,
    calculator: new BowlRunControlCalculator(),
  },
  {
    id: 'bowl.discipline',
    name: 'Bowling Discipline',
    category: MetricCategory.Bowling,
    level: MetricLevel.Composite,
    dependencies: ['bowl.wides', 'bowl.no_balls', 'bowl.overs'],
    version,
    calculator: new BowlDisciplineCalculator(),
  },
  {
    id: 'bowl.wicket_efficiency',
    name: 'Bowling Wicket Efficiency',
    category: MetricCategory.Bowling,
    level: MetricLevel.Composite,
    dependencies: ['bowl.average', 'bowl.strike_rate', 'bowl.wickets', 'bowl.innings'],
    version,
    calculator: new BowlWicketEfficiencyCalculator(),
  },
  {
    id: 'field.impact',
    name: 'Fielding Impact',
    category: MetricCategory.Fielding,
    level: MetricLevel.Composite,
    dependencies: [
      'field.matches',
      'field.dismissals',
      'field.catches',
      'field.stumpings',
      'field.run_outs',
      'field.assisted_run_outs',
    ],
    version,
    calculator: new FieldImpactCalculator(),
  },
  {
    id: 'field.reliability',
    name: 'Fielding Reliability',
    category: MetricCategory.Fielding,
    level: MetricLevel.Composite,
    dependencies: ['field.innings', 'field.dismissals'],
    version,
    calculator: new FieldReliabilityCalculator(),
  },
  {
    id: 'field.activity',
    name: 'Fielding Activity',
    category: MetricCategory.Fielding,
    level: MetricLevel.Composite,
    dependencies: [
      'field.matches',
      'field.innings',
      'field.dismissals',
      'field.catches',
      'field.stumpings',
      'field.run_outs',
      'field.assisted_run_outs',
    ],
    version,
    calculator: new FieldActivityCalculator(),
  },
  {
    id: 'field.catching_impact',
    name: 'Catching Impact',
    category: MetricCategory.Fielding,
    level: MetricLevel.Composite,
    dependencies: ['field.catches', 'field.matches'],
    version,
    calculator: new FieldCatchingImpactCalculator(),
  },
  {
    id: 'field.run_out_impact',
    name: 'Run Out Impact',
    category: MetricCategory.Fielding,
    level: MetricLevel.Composite,
    dependencies: ['field.run_outs', 'field.assisted_run_outs', 'field.matches'],
    version,
    calculator: new FieldRunOutImpactCalculator(),
  },
  {
    id: 'field.dismissal_involvement',
    name: 'Dismissal Involvement',
    category: MetricCategory.Fielding,
    level: MetricLevel.Composite,
    dependencies: ['field.dismissals', 'field.matches', 'field.innings'],
    version,
    calculator: new FieldDismissalInvolvementCalculator(),
  },
]
