import {
  ContextAwayMatchesCalculator,
  ContextFormatsCalculator,
  ContextHomeMatchesCalculator,
  ContextMatchesCalculator,
  ContextNeutralMatchesCalculator,
  ContextOpponentsCalculator,
  ContextSeasonsCalculator,
  ContextTeamsCalculator,
  ContextVenuesCalculator,
} from '../calculators/context/ContextCoreCalculators'
import {
  MetricCategory,
  MetricLevel,
  type MetricDefinition,
} from './types'

const version = '1.0.0'

export const contextCoreMetricDefinitions: readonly MetricDefinition[] = [
  {
    id: 'context.matches',
    name: 'Context Matches',
    category: MetricCategory.Context,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new ContextMatchesCalculator(),
  },
  {
    id: 'context.formats',
    name: 'Formats',
    category: MetricCategory.Context,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new ContextFormatsCalculator(),
  },
  {
    id: 'context.teams',
    name: 'Teams',
    category: MetricCategory.Context,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new ContextTeamsCalculator(),
  },
  {
    id: 'context.opponents',
    name: 'Opponents',
    category: MetricCategory.Context,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new ContextOpponentsCalculator(),
  },
  {
    id: 'context.venues',
    name: 'Venues',
    category: MetricCategory.Context,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new ContextVenuesCalculator(),
  },
  {
    id: 'context.seasons',
    name: 'Seasons',
    category: MetricCategory.Context,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new ContextSeasonsCalculator(),
  },
  {
    id: 'context.home_matches',
    name: 'Home Matches',
    category: MetricCategory.Context,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new ContextHomeMatchesCalculator(),
  },
  {
    id: 'context.away_matches',
    name: 'Away Matches',
    category: MetricCategory.Context,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new ContextAwayMatchesCalculator(),
  },
  {
    id: 'context.neutral_matches',
    name: 'Neutral Matches',
    category: MetricCategory.Context,
    level: MetricLevel.Primitive,
    dependencies: [],
    version,
    calculator: new ContextNeutralMatchesCalculator(),
  },
]
