import {
  BattingStyleTraitCalculator,
  BattingBoundaryTraitCalculator,
  BattingIntentTraitCalculator,
  BattingScoringConsistencyTraitCalculator,
  BowlingStyleTraitCalculator,
  BowlingControlTraitCalculator,
  BowlingEffectivenessTraitCalculator,
  BowlingThreatTraitCalculator,
  FieldingActivityTraitCalculator,
  FieldingImpactTraitCalculator,
  FieldingStyleTraitCalculator,
  WicketKeepingDismissalTraitCalculator,
} from './calculators/TraitCalculators'
import { TraitCategory, type TraitDefinition } from './types'

const version = '1.0.0'

export const traitDefinitions: readonly TraitDefinition[] = [
  {
    id: 'trait.batting_style',
    name: 'Batting Style',
    category: TraitCategory.Batting,
    dependencies: ['bat.intent', 'bat.consistency'],
    version,
    calculator: new BattingStyleTraitCalculator(),
  },
  {
    id: 'trait.batting_intent',
    name: 'Batting Intent Trait',
    category: TraitCategory.Batting,
    dependencies: ['bat.intent'],
    version,
    calculator: new BattingIntentTraitCalculator(),
  },
  {
    id: 'trait.batting_boundary_style',
    name: 'Batting Boundary Style',
    category: TraitCategory.Batting,
    dependencies: ['bat.boundary_intent'],
    version,
    calculator: new BattingBoundaryTraitCalculator(),
  },
  {
    id: 'trait.batting_scoring_consistency',
    name: 'Batting Scoring Consistency Trait',
    category: TraitCategory.Batting,
    dependencies: ['bat.scoring_consistency'],
    version,
    calculator: new BattingScoringConsistencyTraitCalculator(),
  },
  {
    id: 'trait.bowling_style',
    name: 'Bowling Style',
    category: TraitCategory.Bowling,
    dependencies: ['bowl.control', 'bowl.wicket_threat', 'bowl.effectiveness'],
    version,
    calculator: new BowlingStyleTraitCalculator(),
  },
  {
    id: 'trait.bowling_control',
    name: 'Bowling Control Trait',
    category: TraitCategory.Bowling,
    dependencies: ['bowl.control'],
    version,
    calculator: new BowlingControlTraitCalculator(),
  },
  {
    id: 'trait.bowling_wicket_threat',
    name: 'Bowling Wicket Threat Trait',
    category: TraitCategory.Bowling,
    dependencies: ['bowl.wicket_threat'],
    version,
    calculator: new BowlingThreatTraitCalculator(),
  },
  {
    id: 'trait.bowling_effectiveness',
    name: 'Bowling Effectiveness Trait',
    category: TraitCategory.Bowling,
    dependencies: ['bowl.effectiveness'],
    version,
    calculator: new BowlingEffectivenessTraitCalculator(),
  },
  {
    id: 'trait.fielding_style',
    name: 'Fielding Style',
    category: TraitCategory.Fielding,
    dependencies: ['field.impact', 'field.reliability', 'field.activity'],
    version,
    calculator: new FieldingStyleTraitCalculator(),
  },
  {
    id: 'trait.fielding_impact',
    name: 'Fielding Impact Trait',
    category: TraitCategory.Fielding,
    dependencies: ['field.impact'],
    version,
    calculator: new FieldingImpactTraitCalculator(),
  },
  {
    id: 'trait.fielding_activity',
    name: 'Fielding Activity Trait',
    category: TraitCategory.Fielding,
    dependencies: ['field.activity'],
    version,
    calculator: new FieldingActivityTraitCalculator(),
  },
  {
    id: 'trait.keeping_dismissal_involvement',
    name: 'Keeping Dismissal Involvement',
    category: TraitCategory.Fielding,
    dependencies: ['field.reliability'],
    version,
    calculator: new WicketKeepingDismissalTraitCalculator(),
  },
]
